openapi: 3.0.0
info:
  title: Afriex Api V2
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
tags:
  - name: Transactions
paths:
  /v2/orders/qrCode:
    post:
      tags:
        - Transactions
      summary: Get QR Code for Third Party Transaction Order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                senderUserName: TolVa
                recipientUserName: John333
                amount: 3000
                currency: GBP
                clientOrderId: '12345'
                clientId: 62e1495859e8996cc96d72bf
      parameters:
        - name: x-api-key
          in: header
          schema:
            type: string
          example: RANDOM
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                qrCode: >-
                  data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPQAAAD0CAYAAACsLwv+AAAAAklEQVR4AewaftIAAA45SURBVO3BQY4cSRLAQDLR//8yV0c/BZCoamk24Gb2B2utKzysta7xsNa6xsNa6xoPa61rPKy1rvGw1rrGw1rrGg9rrWs8rLWu8bDWusbDWusaD2utazysta7xsNa6xsNa6xo/fEjlb6o4UTmpOFE5qZhUvqniDZWp4g2VqWJSmSp+k8onKiaVqeINlb+p4hMPa61rPKy1rvGw1rrGD19W8U0qb1ScqEwVJxVvVJyoTBWTylQxqZyoTBWTylRxUjGpfKJiUpkq3lCZVE5Upoo3Kr5J5Zse1lrXeFhrXeNhrXWNH36ZyhsVb6hMFZPK36RyUnFSMalMFZPKVHFScaLyTRWTym+qOFH5JpU3Kn7Tw1rrGg9rrWs8rLWu8cNlVN5QmSomlanim1SmiqliUpkqJpWp4psqTlQmlaliUplUpoqTihOVqWJSmSr+nz2sta7xsNa6xsNa6xo/XK7iDZUTlaliUpkqJpUTlZOKSeVE5ZtUpoqTiknlEyonFW9U3ORhrXWNh7XWNR7WWtf44ZdV/E0Vk8pJxUnFpDKpTBUnFScqn6h4Q2WqeENlqphUpopJZaqYVKaKSeVfqvgveVhrXeNhrXWNh7XWNX74MpX/sopJZaqYVKaKSeVEZaqYVKaKSeUTKlPFGypTxU1UpooTlf+yh7XWNR7WWtd4WGtd44cPVdxEZaqYVKaKk4pJZaqYVE5U3qh4Q+WNik9UnFRMKicqJypvVPw/eVhrXeNhrXWNh7XWNX74kMpUMal8U8VU8U0Vk8obKm+onFScqEwqn6iYVCaVNypOVKaKSeWkYlI5qZhUTlS+qeI3Pay1rvGw1rrGw1rrGvYHH1A5qXhDZar4hMobFScqn6h4Q2WqOFH5RMWkMlVMKicVb6hMFZPKN1V8k8pUMamcVHziYa11jYe11jUe1lrXsD/4IpU3KiaVNyo+oXJSMalMFScqJxX/JSpTxaTyiYoTlW+qOFH5RMWkMlVMKlPFNz2sta7xsNa6xsNa6xo//LKKE5Wp4hMqU8VJxYnKGypTxaRyojJVTConFScqJxWTyicq3qg4UTmpmFSmiqliUpkqvqliUpkqPvGw1rrGw1rrGg9rrWv88GUVk8pU8YbKN6lMFScVk8qk8kbF36RyUjGpnFScqEwqU8WkMlVMKicVk8obKlPFpPJGxaTyNz2sta7xsNa6xsNa6xr2B1+kMlX8JpV/qWJS+U0VJypTxYnKVDGpnFRMKlPFGypTxaTyTRX/kspU8YmHtdY1HtZa13hYa13jh39MZaqYVN6omFSmikllqvhExRsqb6hMFZ+omFROKk4qJpWpYlKZKj5RcaJyonJSMalMFScqU8U3Pay1rvGw1rrGw1rrGj/8YxWTylTxmypOVKaKSWWqmFSmipOKN1Q+oTJVTConKlPFicpUMalMFW+oTBVvVJyoTBVvVPymh7XWNR7WWtd4WGtdw/7gF6m8UTGpnFScqJxUnKhMFZPKJyomlaniEypTxaTyiYpJ5RMVf5PKVPGGylQxqbxR8YmHtdY1HtZa13hYa13jhy9TOamYVCaVqeKbKiaVqWKqmFROKj5RMalMFZPKScWkclIxqbxRMam8oTJVTCrfVPGbKk5UvulhrXWNh7XWNR7WWtf44csqvkllqphU3lCZKj5RMamcVEwqU8UbFZ+omFSmihOVk4pJ5aTipGJSmSreUJkqJpU3VKaKSWWq+KaHtdY1HtZa13hYa13D/uADKp+oeEPlN1VMKr+pYlL5popJ5aRiUpkqJpWTin9J5Y2KE5Wp4g2Vk4pPPKy1rvGw1rrGw1rrGvYHH1CZKk5UTiomlZOKSeWk4hMqJxUnKicVk8obFZPKScU3qZxUTConFZPKVDGpTBWTylTxhso3VXzTw1rrGg9rrWs8rLWu8cOHKiaVk4pJ5aTijYo3VE4q3lCZKt5QmSomld+kclIxqUwVb1S8UfGGyhsqU8VJxaQyVZyoTBWfeFhrXeNhrXWNh7XWNewPvkhlqphUPlHxm1S+qWJS+UTFpHJScaIyVXxC5aTiRGWqmFSmik+ovFExqUwVk8pJxTc9rLWu8bDWusbDWusa9gcfUJkqJpU3Kj6hMlVMKm9UTCpvVJyoTBUnKlPFpDJVTCpvVEwqJxVvqPymijdUpopJZaqYVKaKSWWq+KaHtdY1HtZa13hYa13D/uCLVKaKE5XfVHGiMlWcqEwVk8onKt5Q+aaKE5WpYlKZKiaVqWJSmSq+SeU3VUwqJxXf9LDWusbDWusaD2uta/zwIZWp4hMVb6icqJxUnKhMFZPKVDGpfELljYo3VCaVk4pJ5Y2K36QyVbxR8YbKScWkMqlMFZ94WGtd42GtdY2HtdY1fvgylaniEypTxUnFpPKbKk4qJpWpYlKZKiaVN1SmijcqTipOVE4qpopJZao4qZhUPqEyVbyhMlX8poe11jUe1lrXeFhrXeOHL6v4popvqphUpooTlaliUpkq3qiYVD5R8UbFicpUMalMFZPKGxUnKlPFScWkclLxhspU8Tc9rLWu8bDWusbDWusa9gcfUDmpmFT+pYpJZar4m1ROKiaVf6niROWkYlKZKiaVk4pJZao4UfkvqfjEw1rrGg9rrWs8rLWuYX/wH6IyVZyoTBWTylQxqbxR8YbKVPGGyhsVk8pUMalMFZPKScU3qUwVk8o3VUwqv6liUpkqPvGw1rrGw1rrGg9rrWvYH3yRylQxqXyi4kRlqnhD5aTiDZWTikllqjhReaNiUjmpeEPlpGJSmSomlZOKv0nlpGJSmSp+08Na6xoPa61rPKy1rvHDh1ROVE4q3lA5qXhDZar4hMo3qUwVJxWTyqQyVUwqJyonFW9UTCpTxYnKScWkMlVMKp9QmSr+poe11jUe1lrXeFhrXcP+4AMqU8WJylRxonJS8YbKScWJylRxojJVTConFZPKN1V8k8pJxaTyiYpJ5aTiN6l8ouITD2utazysta7xsNa6xg8fqphUTipOVKaKT6hMFZPKGxWTyknFGxWTylTxCZVJ5aRiUpkqTio+UTGpTCqfUDmpmFQ+UTGpfNPDWusaD2utazysta7xw4dUpopJZVI5qZhUpoo3KiaVE5Wp4l+qOFGZKk4qJpWpYlJ5o2JSmSpOKt6oeENlqvimihOVqeKbHtZa13hYa13jYa11DfuDD6hMFZPKVPFNKlPFGypTxb+k8omKSWWqOFE5qZhUTio+oXJScaLyN1W8oTJVfOJhrXWNh7XWNR7WWtewP/iHVN6omFSmikllqnhDZaqYVKaKSeWk4hMqJxUnKlPFicpU8YbKGxVvqEwV36QyVZyonFR808Na6xoPa61rPKy1rmF/8AGVqeJE5Y2KSeWbKj6hMlWcqPxLFZPKVDGpTBUnKlPFGypTxaTyTRWfUJkqTlROKj7xsNa6xsNa6xoPa61r2B98QOWk4kTljYoTlW+qOFE5qZhUpopJZao4UflNFZPKScUbKlPFpHJSMalMFd+kMlWcqJxUfNPDWusaD2utazysta5hf/AXqZxUnKhMFZ9QmSpOVE4q3lCZKr5JZap4Q2WqmFSmiknlpGJSeaNiUpkqTlSmiknljYoTlZOKTzysta7xsNa6xsNa6xo/fEjlpOINlZOKSWWqmFROKiaVNyomlaliUjlRmSpOVE4q3lB5o+KNikllqphUpopJZaqYVKaKqWJSmSomlaliUvmXHtZa13hYa13jYa11DfuDD6icVJyoTBVvqEwVk8pJxf8TlaliUjmpmFS+qeITKn9TxaRyUjGpnFScqEwVn3hYa13jYa11jYe11jV++MtUTlR+U8WkclIxqZxUnKhMFZPKVDFVTConFZPKScWJylQxqZxUTCpTxRsqU8UbKlPFicpU8YbKVPFND2utazysta7xsNa6xg8fqphUJpWp4l9SmSreqHhD5URlqphUflPFpHJSMamcVEwqJypTxaTyhsonVKaKSWWq+Jce1lrXeFhrXeNhrXUN+4O/SGWqOFGZKk5UflPFicpUMamcVLyh8k0Vk8pJxaRyUjGpnFS8oXJSMan8SxXf9LDWusbDWusaD2uta9gf/B9TOamYVN6omFTeqHhD5RMVb6i8UTGpnFRMKicV36TyRsUbKlPFicpJxSce1lrXeFhrXeNhrXWNHz6k8jdVTBUnKlPFpPJNFZPKVDGpTBWTylQxqZyoTBUnFZPKScWJylQxqZyofFPFpHKiMlWcqJxU/KaHtdY1HtZa13hYa13jhy+r+CaVE5WpYqo4qZhUPqEyVbyh8k0Vb6h8QmWqOKmYVH6TyhsVn6iYVKaKb3pYa13jYa11jYe11jV++GUqb1R8k8pUMalMFScVk8obKicVk8obKr9J5aRiUpkqJpVPVEwqJxWTyqTyiYpJ5W96WGtd42GtdY2HtdY1friMyidUflPFicpUMam8UTGpnFRMKlPFpHJS8YmKf6niDZWp4m96WGtd42GtdY2HtdY1frhMxaTyRsWkMlWcqEwqJxVvVEwqJypTxYnKVDGpnKh8omJS+UTFScWkMqm8UXGiclLxiYe11jUe1lrXeFhrXeOHX1bxmyomlaniExWTylQxVZyoTCpTxaRyUjGpTBVvVEwqU8WkclIxqbxRMam8oTJVTConFW+oTBUnFd/0sNa6xsNa6xoPa61r/PBlKn+TylQxqZxUTCpTxRsqJxWTyhsVk8obKlPFpHKiMlVMKpPKJ1ROKiaVE5WpYlKZVKaKSeWNit/0sNa6xsNa6xoPa61r2B+sta7wsNa6xsNa6xoPa61rPKy1rvGw1rrGw1rrGg9rrWs8rLWu8bDWusbDWusaD2utazysta7xsNa6xsNa6xoPa61r/A/V7yMWatgXDQAAAABJRU5ErkJggg==
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
              example:
                error: Invalid Request, sender and recipient usernames must be valid
  /v2/users/{ukCustomerId}/transactions:
    get:
      tags:
        - Transactions
      summary: Get Transactions By User Id
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{ukCustomerJWTAuthHeader}}
        - name: ukCustomerId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                transactions: []
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
              example:
                error: Authorization header is missing
